module CardDealer
  class BuildDeck
    def self.custom: (
        ?decks: Integer,
        ?cards_per_suit: Integer,
        ?ranks: :highest | :lowest | Array[String],
        ?suits: :all | Array[String]) -> Deck

    def self.standard52: (?decks: Integer) -> Deck

    def self.standard36: (?decks: Integer) -> Deck

    private

    def self.build_ranks: (:highest | :lowest | Array[String] ranks, Integer cards_per_rank) -> Array[String]

    def self.build_suits: (:all | Array[String] suits) -> Array[String]

    def self.build_deck: (Integer decks, Array[String] ranks, Array[String] suits) -> Deck
  end
end
