module CardDealer
  class Card
    CLUBS: 'c'
    DIAMONDS: 'd'
    HEARTS: 'h'
    SPADES: 's'

    RANKS: Array[String]
    SUITS: Array[String]

    RANKS_SET: Set[String]
    SUITS_SET: Set[String]

    @to_s: String

    attr_reader rank: String
    attr_reader suit: String

    def initialize: (rank: String, suit: String | nil) -> void

    def to_s: -> String

    def eql?: (other: Card) -> bool

    private

    def validate_arguments: (rank: String, suit: String) -> void
  end
end
