module CardDealer
  class Deck
    attr_reader cards: Array[Card]
    attr_reader seed: Integer?
    attr_reader burned_cards: Array[Card]?

    def self.from_binary: (String) -> Deck

    def initialize: (Array[Card] cards) -> void

    def shuffle: (?Integer seed) -> self

    def deal: (?Integer num, ?burn: Integer) -> Array[Card]

    def size: -> Integer

    def to_a: -> Array[String]

    def to_s: -> String

    def to_binary_s: -> String
  end
end
